CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_login ON users(login);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  number TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'NEW' CHECK (status in ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED')),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ NULL,
  processing_since TIMESTAMPTZ NULL,
  is_ready boolean GENERATED ALWAYS AS (
    status = 'NEW'
    OR (status = 'PROCESSING' AND processing_since < NOW() - interval '5 minutes')
  ) STORED
);

CREATE INDEX IF NOT EXISTS idx_orders_user
ON orders (user_id);

CREATE INDEX IF NOT EXISTS idx_orders_status_incomplete
ON orders (uploaded_at ASC)
WHERE is_ready;

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_number TEXT,
  amount INTEGER NOT NULL DEFAULT 0,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS transactions_order_number_unique 
ON transactions (order_number)
WHERE order_number is not NULL;

CREATE INDEX IF NOT EXISTS idx_transactions_user_id_withdrawals
ON transactions (user_id, uploaded_at DESC)
WHERE amount < 0;

CREATE INDEX IF NOT EXISTS idx_transactions_user_id
ON transactions (user_id);
