CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  number TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'NEW' CHECK (status in ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED')),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ NULL,
  processing_since TIMESTAMPTZ NULL
);

CREATE INDEX idx_orders_new
ON orders (uploaded_at ASC)
WHERE status = 'NEW';

CREATE INDEX idx_orders_processing_ready
ON orders (processing_since, uploaded_at ASC)
WHERE status = 'PROCESSING';

CREATE INDEX IF NOT EXISTS idx_orders_user
ON orders (user_id, uploaded_at DESC);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_number TEXT,
  amount INTEGER NOT NULL DEFAULT 0,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS transactions_order_number_unique 
ON transactions (order_number)
WHERE order_number is not NULL;

CREATE INDEX IF NOT EXISTS idx_transactions_user_withdrawals
ON transactions (user_id, processed_at DESC)
WHERE amount < 0;

CREATE INDEX IF NOT EXISTS idx_transactions_user
ON transactions (user_id);
