// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/georgg2003/gophermart/internal/repository (interfaces: Repository,AccrualRepo)
//
// Generated by this command:
//
//	mockgen -destination ./mock/mock.go -package mock . Repository,AccrualRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApplyOrderAccrual mocks base method.
func (m *MockRepository) ApplyOrderAccrual(ctx context.Context, orderNumber string, accrual int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyOrderAccrual", ctx, orderNumber, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyOrderAccrual indicates an expected call of ApplyOrderAccrual.
func (mr *MockRepositoryMockRecorder) ApplyOrderAccrual(ctx, orderNumber, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyOrderAccrual", reflect.TypeOf((*MockRepository)(nil).ApplyOrderAccrual), ctx, orderNumber, accrual)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, login, passwordHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, login, passwordHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, login, passwordHash)
}

// CreateUserOrder mocks base method.
func (m *MockRepository) CreateUserOrder(ctx context.Context, userID int64, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserOrder indicates an expected call of CreateUserOrder.
func (mr *MockRepositoryMockRecorder) CreateUserOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserOrder", reflect.TypeOf((*MockRepository)(nil).CreateUserOrder), ctx, userID, orderNumber)
}

// CreateUserWithdrawal mocks base method.
func (m *MockRepository) CreateUserWithdrawal(ctx context.Context, userID int64, orderNumber string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithdrawal", ctx, userID, orderNumber, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserWithdrawal indicates an expected call of CreateUserWithdrawal.
func (mr *MockRepositoryMockRecorder) CreateUserWithdrawal(ctx, userID, orderNumber, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithdrawal", reflect.TypeOf((*MockRepository)(nil).CreateUserWithdrawal), ctx, userID, orderNumber, amount)
}

// GetOrderToProcess mocks base method.
func (m *MockRepository) GetOrderToProcess(ctx context.Context, processRetryTimeout int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderToProcess", ctx, processRetryTimeout)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderToProcess indicates an expected call of GetOrderToProcess.
func (mr *MockRepositoryMockRecorder) GetOrderToProcess(ctx, processRetryTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderToProcess", reflect.TypeOf((*MockRepository)(nil).GetOrderToProcess), ctx, processRetryTimeout)
}

// GetUserBalance mocks base method.
func (m *MockRepository) GetUserBalance(ctx context.Context, userID int64) (*models.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*models.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockRepositoryMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockRepository)(nil).GetUserBalance), ctx, userID)
}

// GetUserByLogin mocks base method.
func (m *MockRepository) GetUserByLogin(ctx context.Context, login string) (*models.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*models.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockRepository)(nil).GetUserByLogin), ctx, login)
}

// GetUserOrders mocks base method.
func (m *MockRepository) GetUserOrders(ctx context.Context, userID int64) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockRepositoryMockRecorder) GetUserOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockRepository)(nil).GetUserOrders), ctx, userID)
}

// GetUserWithdrawals mocks base method.
func (m *MockRepository) GetUserWithdrawals(ctx context.Context, userID int64) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockRepositoryMockRecorder) GetUserWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockRepository)(nil).GetUserWithdrawals), ctx, userID)
}

// SetOrderStatus mocks base method.
func (m *MockRepository) SetOrderStatus(ctx context.Context, orderNumber string, orderStatus models.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderStatus", ctx, orderNumber, orderStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrderStatus indicates an expected call of SetOrderStatus.
func (mr *MockRepositoryMockRecorder) SetOrderStatus(ctx, orderNumber, orderStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderStatus", reflect.TypeOf((*MockRepository)(nil).SetOrderStatus), ctx, orderNumber, orderStatus)
}

// MockAccrualRepo is a mock of AccrualRepo interface.
type MockAccrualRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualRepoMockRecorder
	isgomock struct{}
}

// MockAccrualRepoMockRecorder is the mock recorder for MockAccrualRepo.
type MockAccrualRepoMockRecorder struct {
	mock *MockAccrualRepo
}

// NewMockAccrualRepo creates a new mock instance.
func NewMockAccrualRepo(ctrl *gomock.Controller) *MockAccrualRepo {
	mock := &MockAccrualRepo{ctrl: ctrl}
	mock.recorder = &MockAccrualRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualRepo) EXPECT() *MockAccrualRepoMockRecorder {
	return m.recorder
}

// GetOrderAccrual mocks base method.
func (m *MockAccrualRepo) GetOrderAccrual(ctx context.Context, orderNumber string) (*models.GetOrderAccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(*models.GetOrderAccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderAccrual indicates an expected call of GetOrderAccrual.
func (mr *MockAccrualRepoMockRecorder) GetOrderAccrual(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderAccrual", reflect.TypeOf((*MockAccrualRepo)(nil).GetOrderAccrual), ctx, orderNumber)
}
