// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package restapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OrderInfoStatus.
const (
	INVALID    OrderInfoStatus = "INVALID"
	NEW        OrderInfoStatus = "NEW"
	PROCESSED  OrderInfoStatus = "PROCESSED"
	PROCESSING OrderInfoStatus = "PROCESSING"
)

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	Current   float32 `json:"current"`
	Withdrawn float32 `json:"withdrawn"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// OrderInfo defines model for OrderInfo.
type OrderInfo struct {
	Accrual    *float32        `json:"accrual,omitempty"`
	Number     string          `json:"number"`
	Status     OrderInfoStatus `json:"status"`
	UploadedAt time.Time       `json:"uploaded_at"`
}

// OrderInfoStatus defines model for OrderInfo.Status.
type OrderInfoStatus string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// WithdrawRequest defines model for WithdrawRequest.
type WithdrawRequest struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// WithdrawalInfo defines model for WithdrawalInfo.
type WithdrawalInfo struct {
	Order       string    `json:"order"`
	ProcessedAt time.Time `json:"processed_at"`
	Sum         float32   `json:"sum"`
}

// PostApiUserOrdersTextBody defines parameters for PostApiUserOrders.
type PostApiUserOrdersTextBody = string

// PostApiUserBalanceWithdrawJSONRequestBody defines body for PostApiUserBalanceWithdraw for application/json ContentType.
type PostApiUserBalanceWithdrawJSONRequestBody = WithdrawRequest

// PostApiUserLoginJSONRequestBody defines body for PostApiUserLogin for application/json ContentType.
type PostApiUserLoginJSONRequestBody = LoginRequest

// PostApiUserOrdersTextRequestBody defines body for PostApiUserOrders for text/plain ContentType.
type PostApiUserOrdersTextRequestBody = PostApiUserOrdersTextBody

// PostApiUserRegisterJSONRequestBody defines body for PostApiUserRegister for application/json ContentType.
type PostApiUserRegisterJSONRequestBody = RegisterRequest
