// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package restapi

import (
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса
	// (GET /api/user/balance)
	GetAPIUserBalance(ctx echo.Context) error
	// Списание баллов
	// (POST /api/user/balance/withdraw)
	PostAPIUserBalanceWithdraw(ctx echo.Context) error
	// Аутентификация пользователя
	// (POST /api/user/login)
	PostAPIUserLogin(ctx echo.Context) error
	// Получение списка заказов пользователя
	// (GET /api/user/orders)
	GetAPIUserOrders(ctx echo.Context) error
	// Загрузка номера заказа
	// (POST /api/user/orders)
	PostAPIUserOrders(ctx echo.Context) error
	// Регистрация пользователя
	// (POST /api/user/register)
	PostAPIUserRegister(ctx echo.Context) error
	// История списаний
	// (GET /api/user/withdrawals)
	GetAPIUserWithdrawals(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAPIUserBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetAPIUserBalance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAPIUserBalance(ctx)
	return err
}

// PostAPIUserBalanceWithdraw converts echo context to params.
func (w *ServerInterfaceWrapper) PostAPIUserBalanceWithdraw(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAPIUserBalanceWithdraw(ctx)
	return err
}

// PostAPIUserLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAPIUserLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAPIUserLogin(ctx)
	return err
}

// GetAPIUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) GetAPIUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAPIUserOrders(ctx)
	return err
}

// PostAPIUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) PostAPIUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAPIUserOrders(ctx)
	return err
}

// PostAPIUserRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostAPIUserRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAPIUserRegister(ctx)
	return err
}

// GetAPIUserWithdrawals converts echo context to params.
func (w *ServerInterfaceWrapper) GetAPIUserWithdrawals(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAPIUserWithdrawals(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/balance", wrapper.GetAPIUserBalance)
	router.POST(baseURL+"/api/user/balance/withdraw", wrapper.PostAPIUserBalanceWithdraw)
	router.POST(baseURL+"/api/user/login", wrapper.PostAPIUserLogin)
	router.GET(baseURL+"/api/user/orders", wrapper.GetAPIUserOrders)
	router.POST(baseURL+"/api/user/orders", wrapper.PostAPIUserOrders)
	router.POST(baseURL+"/api/user/register", wrapper.PostAPIUserRegister)
	router.GET(baseURL+"/api/user/withdrawals", wrapper.GetAPIUserWithdrawals)

}
