// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package restapi

import (
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса
	// (GET /api/user/balance)
	GetApiUserBalance(ctx echo.Context) error
	// Списание баллов
	// (POST /api/user/balance/withdraw)
	PostApiUserBalanceWithdraw(ctx echo.Context) error
	// Аутентификация пользователя
	// (POST /api/user/login)
	PostApiUserLogin(ctx echo.Context) error
	// Получение списка заказов пользователя
	// (GET /api/user/orders)
	GetApiUserOrders(ctx echo.Context) error
	// Загрузка номера заказа
	// (POST /api/user/orders)
	PostApiUserOrders(ctx echo.Context) error
	// Регистрация пользователя
	// (POST /api/user/register)
	PostApiUserRegister(ctx echo.Context) error
	// История списаний
	// (GET /api/user/withdrawals)
	GetApiUserWithdrawals(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiUserBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiUserBalance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiUserBalance(ctx)
	return err
}

// PostApiUserBalanceWithdraw converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiUserBalanceWithdraw(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiUserBalanceWithdraw(ctx)
	return err
}

// PostApiUserLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiUserLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiUserLogin(ctx)
	return err
}

// GetApiUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiUserOrders(ctx)
	return err
}

// PostApiUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiUserOrders(ctx)
	return err
}

// PostApiUserRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiUserRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiUserRegister(ctx)
	return err
}

// GetApiUserWithdrawals converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiUserWithdrawals(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiUserWithdrawals(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/balance", wrapper.GetApiUserBalance)
	router.POST(baseURL+"/api/user/balance/withdraw", wrapper.PostApiUserBalanceWithdraw)
	router.POST(baseURL+"/api/user/login", wrapper.PostApiUserLogin)
	router.GET(baseURL+"/api/user/orders", wrapper.GetApiUserOrders)
	router.POST(baseURL+"/api/user/orders", wrapper.PostApiUserOrders)
	router.POST(baseURL+"/api/user/register", wrapper.PostApiUserRegister)
	router.GET(baseURL+"/api/user/withdrawals", wrapper.GetApiUserWithdrawals)

}
